apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rezervace-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: rezervace.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rezervace-app
                port:
                  number: 80
